<!-- \addtocontents{toc}{\setcounter{tocdepth}{1}} -->
\addtocontents{toc}{\setcounter{tocdepth}{0}}

\newpage
\thispagestyle{plain}
\mbox{}
\pagecolor{black}
\color{white}

# General introduction

> "*Zij zag, zij zag, wat niemand zag.*

> *Maar ach, voor haar kwam toch een dag*

> *Dat zij het niet precies kon zien*

> *Heeft u dat ook misschien*"

>
> --- Heinz Hermann Polzer

------------------------------------------------------------------------

\newpage
\nopagecolor
\color{black}
\linespread{1.213}

## Research in context {.unnumbered}

This thesis focuses on survival prediction models in liver transplantation (LT). Predicting survival is important because it is used to prioritize patients in need of transplantation. Many patients are not transplanted in time, due to the shortage of donor liver grafts.^1,2^ Optimizing survival prediction models is therefore a matter of life and death.

### A short history of liver transplantation {.unnumbered}

The shortage of donor liver grafts and the subsequent need for survival prediction exist because of the success of LT as treatment. Thomas Starzl was the first to perform a LT in 1963, trying to save a severely ill child.^3^ In this first and later attempts, patients often died shortly after transplantation. Only a laboratory pig managed to survive many years without immunosuppression and therefore became his favorite transplant mascot.^4^ Performing LT remained an experimental treatment until further improvements in immunosuppression, operation and preservation techniques, diagnosis of liver diseases, and postoperative management had been made.^5,6^ In the late 70s the early LT programs started, in 1983 LT was declared not experimental anymore, and only in the 90s many other LT centers started. Five-year post-transplant survival probabilities increased from 21% to 71% in 25 years.^7^

Through these improvements, an increasing diversity and number of patients were eligible and could be treated.^5^ This created shortages of donor livers, as the number of patients in need of LT (‘LT candidates’) outnumbered the available donor livers. Even now, despite the development of donation after circulatory death, living donor liver transplantation, and machine perfusion for marginal organs, the imbalance between available donor organs and number of candidates persists, with an average waiting time for LT of five months in the Eurotransplant region and eight months in the United Network for Organ Sharing (UNOS) regions.^1,2^ As a result, nowadays many patients are still not transplanted in time and die on the waiting list. For the Eurotransplant region in 2020, 25.3% (374/1481) of the LT candidates died on the waiting list.^1^ In the US in 2019, LT came too late for 18.3% (2405/13,093) of the waiting patients.^2^ Indeed, the mortality of patients on the liver waiting list is highest compared to all other transplantable organs. Therefore, the development and improvement of survival prediction for the LT waiting list is most important.

### The start of liver allocation {.unnumbered}

Because of the plethora of indications and increasing number of patients listed for LT, donated liver grafts needed to be distributed in a systematic and just way. Thus, the field of liver allocation came into existence, where allocation can be defined as “the process of giving someone their part of a total amount of something to use in a particular way”.^8^
Initially, liver grafts were assigned to patients without applying uniform rules, because there were only a small number of patients and grafts involved. Then, following the field of kidney allocation, LT was offered based on waiting time, i.e., first come first served.^5^ With an increasing number of patients involved, waiting times increased and therefore governmental regulation was initiated, which gave rise to organ procurement organizations (OPO). Importantly, it was shown that waiting time did not correlate well with waiting list mortality.^9^ Thus, consensus was reached that the most relevant consideration was not how long a patient had waited, but what the risk of death was while waiting. In other words, the principle of transplanting the sickest first was employed.^10^ As a result, the OPO’s effectuated policies that sought to incorporate measures of disease severity into allocation. The rationale was that prioritizing patients with the highest expected mortality without LT would reduce deaths among waiting patients.

### Survival prediction {.unnumbered}

Because liver allocation aims to prioritize patients who will die soonest without transplantation, it is important to understand survival prediction models.

Clinical information of a patient can relate to the true patient state that is either currently present (diagnosis) or will be present in the future (prognosis).^11^ In the setting of survival prediction, future survival (prognosis) of a patient is estimated. Typically, only some patients will experience the event of interest (death) within the studied time. Therefore, survival times will be unknown for many patients, which is known as censoring of outcome.^12^ Right censoring can occur because (1) the patient did not die yet, (2) because the patient was lost during study follow-up, or (3) another event took place which disabled further follow-up (e.g., transplantation prevented further follow-up for death on the waiting list). The fact that patients can be censored makes survival analysis difficult, as the aim is to use all the available information and to not discard follow-up times of patients without the event. In the setting of LT and this thesis, survival analysis will mostly be done for LT candidates on the waiting list. The survival probability on the waiting list is the chance that a patient survives from a specified time of origin (e.g., first registration) until a future time point (e.g., 90 days). Post-transplant survival will also be used in chapter \@ref(chap-benefit) of this thesis and is defined as the probability of survival from the moment of transplantation to the earliest of post-transplant death, loss to follow-up, or end of study.

When predicting survival, it is important to consider that patient characteristics can affect survival and that these characteristics can be differently distributed within the studied population. For example, older patients might more frequently have more severe disease. The Cox proportional hazards model is used to study the impact of one variable, adjusted for the impact of other variables, and to estimate the effect size of each variable.^13^ For the above mentioned example, a Cox model could show that for two patients with the disease severity, a higher age would increase the risk of death. The probability that a patient on the waiting list dies at a given moment is called the hazard $h(t)$: \[h(t) = h_{0}(t) \times e^{b_{1}x_{1} + b_{2}x_{2} + ...}\] This formula shows that the hazard depends on the chosen time $t$, which seems likely for the waiting list. It also depends on chosen predictors $(x_{1},x_{2},..)$ that have a certain impact, which is expressed through the size of the coefficients $(b_{1},b_{2},..)$. The baseline hazard $h_{0}$ is the hazard if all predictors $(x_{1},x_{2},..)$ were set to zero. For example, if age were used to predict survival, $h_{0}$ would be the instantaneous risk of death at age 0.

### Measuring model prediction performance {.unnumbered}

The outcome of analysis is often binary (death or alive) and therefore predictions of this outcome can be expressed as absolute risks (e.g., 60% chance of dying in the next five years). Because the aim is to best estimate the true future patient state, it is important to assess performance of a prediction model. The first essential measure is discrimination, which assesses whether the model can discriminate between patients based on their risks of the outcome (e.g., death). Patients with the event should have higher risk estimates than patients without the event. For allocation purposes, this means that patients with a higher risk of death will be ranked above patients with lower risks. Therefore, good model discrimination is essential for allocation. Discrimination is often expressed through the concordance statistic (or c-index). Imagine that the prediction model is offered information on two patients from the population and that it must decide which patient has a higher risk of death than the other. The percentage of correct decisions by the model corresponds to the c-index. A c-index of 0.5 means that the model is as good as flipping a coin. A c-index of 1 means that a model perfectly ranks patients, which in practice is not possible. In real cohort data, a c-index above 0.8 is considered excellent.

The next essential measure of model performance is calibration, which measures model accuracy. In other words, calibration tells how well the predicted risks match the observed risks in the studied population. Discrimination indicates which patient has a higher risk, but it tells nothing about the value of that risk (e.g., 10% or 90% chance of death). Calibration assesses the absolute risks and therefore is essential for research and communication with patients.^14^ For example, clinicians and patients may make decisions based on the expected risk for an event (e.g., decide to transplant a patient based on an expected high risk of death without treatment). Strong over- or underestimation of these risks are unacceptable for clinical practice.^15^ Thus, survival prediction models aim to estimate future survival, which is essential for allocation of scarce liver grafts.

### The MELD score {.unnumbered}
Several survival prediction models have previously been applied in liver allocation. Perhaps the most noteworthy is the Child-Turcotte-Pugh (CTP) score, which was the first widespread model used to reflect patient disease severity for the LT waiting list.^16^ Although this score was a well-established predictor of mortality in cirrhotic patients, it failed in effective sickest-first allocation for several reasons. One important limitation was that patients were categorized in only three groups. These groups still encompassed many patients with varying disease severity and therefore risk stratification was not precise. Also, within each group, waiting time was still used as main prioritizing principle. Another important limitation of the CTP score was the subjective grading of ascites and encephalopathy, which could lead to inter-observer variability when scoring disease severity.^17^ To reach a more reproducible and objective representation of disease, the Model for End-stage Liver Disease (MELD) was considered.

The MELD score was developed in the Mayo Clinic to predict early survival after transjugular intrahepatic portosystemic shunt (TIPS) placement in 231 cirrhotic patients.^18^ These patients received TIPS to prevent variceal rebleeding and to treat refractory ascites. The seminal study by Malinchoc et al. found that three blood measurements best predicted survival, i.e., serum bilirubin, creatinine, and the international normalized ratio for prothrombin time (INR). After validation in 71 Dutch patients, the original MELD equation was proposed: 
\linespread{1}
\begin{align*}
\ MELD = 9.57\times ln(creatinine) + 3.78\times ln(bilirubin) +\\
\ 11.2\times ln(INR) + 6.43 \times(cause of cirrhosis)
\end{align*}
\linespread{1.213}
Because survival after TIPS mainly depended on the severity of liver disease, it was hypothesized that MELD was also suitable for survival prediction in patients without TIPS. Thus, retrospective validation was done to investigate whether MELD could also be applied to different etiologies and severities of liver disease.^19^ It was found that the cause of cirrhosis could be excluded from the equation without lowering predictive performance. Thus, the final form became: 
<!-- \begin{align*}  -->
<!-- \ MELD = 9.57\times ln(creatinine) + 3.78\times ln(bilirubin) +\\  -->
<!-- \ 11.2\times ln(INR) + 6.43 -->
<!-- \end{align*}  -->
\linespread{1}
\begin{align*}
\ MELD = 9.57\times ln(creatinine) + 3.78\times ln(bilirubin) +\\
\ 11.2\times ln(INR) + 6.43
\end{align*}
\linespread{1.213}
Then, because it was considered as potential allocation model, MELD was prospectively evaluated by ranking patients on the waiting list.^20^ In 2002, MELD was applied as the basis of liver allocation in the United States (US). In 2006, the Eurotransplant region followed. In 2016, the US progressed to a newer form of MELD: the MELD sodium (MELD-Na) score.^21^ However, MELD has remained unchanged as the main driver for liver allocation in the Eurotransplant region.

<!-- \chaptermark{Central argument} -->

## Justifying why research is needed: central argument {.unnumbered}
In the Eurotransplant region, the fundamental model that predicts survival for liver allocation has remained unchanged since 2006. It is therefore easy to see the gap this thesis aims to fill. The current LT allocation system prioritizes the sickest patients, based on estimated survival on the waiting list. Thus, the primary goal of this thesis is to improve models that predict survival in LT candidates. These improved models could help to distribute liver grafts in the best way possible. To understand the possible improvements, some current problems are outlined below.

<!-- \chaptermark{Research questions} -->

## Thesis layout: research questions and addressed problems {.unnumbered}

### Considering sodium {.unnumbered}
The MELD score uses three blood measurements, i.e., serum bilirubin, creatinine, and the INR. In cirrhotic patients, hyponatremia indicates worse survival.^22,23^ This is because the kidneys fail to compensate lowered splanchnic blood pressure caused by cirrhosis-induced vasodilatation. As such, hyponatremia does not represent kidney failure per se, but it indicates a decompensation of regulating systems in a setting of portal hypertension. It was shown that sodium (Na) affected death risk corrected for MELD.^24–26^ Therefore, the addition of sodium (Na) to MELD (MELD-Na) was investigated in the US. Important advantages of serum sodium were that it was readily available and could be measured reliably and objectively. Results showed that MELD-Na better predicted survival on the waiting list and therefore possibly enabled better sickest-first LT allocation.^21^ In 2016, the US implemented MELD-Na as the basis of LT allocation. Subsequent evaluation indeed showed a reduction in waiting list mortality.^27^ Thus, as a starting point for this thesis, it was suggested to validate MELD-Na for the Eurotransplant region. Therefore, in **Chapter \@ref(chap-meldna)**, we hypothesized that MELD-Na would also improve LT candidate survival prediction in the Eurotransplant region.

### Updating coefficients {.unnumbered}
After validating MELD-Na, the author questioned whether the current forms of MELD and MELD-Na were suitable for the Eurotransplant region. This question arose because a model best represents the population it is fit in. As the MELD score was fitted 20 years ago in 231 US patients,^18^ it was assumed to be a bad representation of the current Eurotransplant population. Therefore, in **Chapter \@ref(chap-refit)**, the second question posed in this thesis was whether refitting MELD for the Eurotransplant region would improve survival prediction. To understand what refitting means and how improvements could be made, consider the above-mentioned MELD equation. It shows three parameters (bilirubin, creatinine, and INR) and their coefficient (relative weight). The values of these coefficients represent the relations of the variables to survival in the studied population. However, MELD’s coefficients were set in a small (n=231) and likely unrepresentative population.^18^ Population changes (most notably disease incidence) have decreased MELD’s predictive power over the years.^28^ Even in the US, updating MELD showed an improvement in survival prediction.^29,30^ We hypothesized that in a different population, like the Eurotransplant region, MELD variables relation to survival would be different. It is remarkable that the Eurotransplant region has been using a MELD equation that is 20 years old. Thousands of patients have been prioritized based on an unadjusted and possibly suboptimal model.

### Past and current disease {.unnumbered}
When refitting MELD, the question arose why only one baseline measurement was used to fit the model. The third problem addressed in this thesis therefore was that current survival prediction for LT prioritization is based on one moment in time, i.e., the last available measurement of MELD. This is not the moment the model was fit for. Previous measurements are also ignored. In the Eurotransplant region at the end of 2020, patients on the LT waiting list spent a median time of 10 months waiting ( _Eurotransplant public statistics library: 3085P_All ET_ ). During this time, disease develops and expected survival changes. This past course of disease encompasses valuable information for the future survival probability and thus patient priority for LT. Although it is currently ignored by MELD, in clinical practice it would be considered undesirable to ignore previous disease information. 

In **Chapter \@ref(chap-jm)** we hypothesized that using both previous and current disease severity to predict survival would be an improvement. The idea was to better mimic clinical survival prediction, as an experienced clinician would consider both previous and current disease development to estimate patient prognosis. To achieve this, joint models (JMs) were applied.^31^ The JM combines longitudinal and survival analysis. This way, complex questions can be answered, such as: what is the effect of a change in MELD over time on future patient survival? Importantly, JMs yield predictions that are dynamic (updated based on accumulating evidence) and personalized (for the population average and individual). However, JMs were never applied on a large scale in medicine, also not in the field of LT.

### Acute-on-chronic liver disease {.unnumbered}
Most patients on the LT waiting list have chronic liver disease, which gradually worsens in severity. However, some patients can develop acute-on-chronic liver failure (ACLF). ACLF is a syndrome characterized by three major features: systemic inflammation, relationship with precipitating events (e.g., infections or alcoholic hepatitis), and an association with single- or multi-organ failure.^32^ As a result, in ACLF mortality is high and a proportion of these patients urgently needs LT for treatment. However, the MELD score underestimates mortality in ACLF, because it ‘only’ measures liver and kidney failure.^33^ In **Chapter \@ref(chap-aclfjm)**, JMs were applied to model disease and survival in patients with ACLF. We proposed that the dynamic JMs would be valuable in ACLF, because ACLF disease severity and mortality change rapidly over time.^34^ The JM can consider both the value of disease severity and its rate of change at each moment in time. Analogous to speed, one can measure a value (e.g., 15 m/s) and a rate of change (e.g., an acceleration of 5 m/s^2^). The rate of change indicates worsening, stable, or improving disease severity, which is valuable prognostic information.

### Benefit of transplantation: life years gained {.unnumbered}
The LT waiting list prioritizes the sickest patients to receive transplantation offers first. It is based on the principle of urgency, to prevent deaths on the waiting list. However, this ignores post-transplant outcomes, which, in an extreme example, could result in transplanting patients who die the next day. Also, patients could be transplanted even though it does more harm than good.^35^ An alternative principle of allocation could be based on survival benefit, or the life years gained from transplantation.^36^ Survival benefit is calculated by comparing the estimated survival with and without LT. For the clinician, it is intuitive to weigh the possible consequences of (not) treating a patient. This is especially true for LT, because it is a treatment with inherent increased risk of death due to surgery and e.g. infections due to post-transplant immunosuppression.^37^ Also, there are far more patients in need of transplantation than there are available liver grafts,^1,2^ which further necessitates the prevention of futile LT.^38,39^ 

Thus, it is relevant to investigate whether and to what extend patients gain life years from LT. In **Chapter \@ref(chap-benefit)**, survival benefit of US LT candidates is estimated. A survival benefit comparison is made between patients with and without hepatocellular carcinoma (HCC). This is done because survival with and without LT is different between (non-)HCC patients.^40,41^ Allocation also differs between HCC and non-HCC-patients, because MELD(-Na) fails to adequately predict survival in patients with HCC. To compensate this inadequacy, an alternative system of artificial exception points was devised.^42^ Although the aim of the exception point system was to equalize LT access, in practice HCC patients have gained too much LT access.^43–45^ 
In the Eurotransplant exception system, eligible HCC patients receive an initial MELD score that equals 10% (MELD 20) or 15% (MELD 22) 90-day mortality, depending on the country of listing. The initial MELD score is then increased with 10% mortality every 90 days, which intends to mimic tumor progression. It is however evident that exception points fail to represent patient characteristics and are arbitrary. Although the aim of the exception point system was to equalize LT access, in practice HCC patients gained too much LT access.^43–45^ Survival benefit, based on actual patient characteristics, could therefore serve as equalizing principle for survival prediction and allocation.

In **Part IV**, this thesis will be summarized, discussed, and provided with future perspectives. The appendix provides two supplementary chapters. Lastly, a **summary in Dutch** will be given.

\newpage

\chaptermark{References}
\linespread{1}
\small

## References {.unnumbered}
1. Eurotransplant International Foundation. Annual Report 2020.; 2020.
2. Kwong AJ, Kim WR, Lake JR, et al. OPTN/SRTR 2019 Annual Data Report: Liver. Am J Transplant. 2021;21(S2):208-315. doi:10.1111/ajt.16494
3. Starzl TE, Marchioro TL, Von Kaulla KN, Hermann G, Brittain RS, Wadell WR. Transplantation of the liver. Surg Gynecol Obs. 1963;117(2):659-676. doi:10.1097/00000658-197808000-00001
4. Starzl TE. The Puzzle People: Memoirs of a Transplant Surgeon. University of Pittsburgh Press; 1992.
5. Merion RM, Sharma P, Mathur AK, Schaubel DE. Evidence-based development of liver allocation: A review. Transpl Int. 2011;24(10):965-972. doi:10.1111/j.1432-2277.2011.01274.x
6. Zarrinpar A, Busuttil RW. Liver transplantation: Past, present and future. Nat Rev Gastroenterol Hepatol. 2013;10(7):434-440. doi:10.1038/nrgastro.2013.88
7. Dutkowski P, De Rougemont O, Müllhaupt B, Clavien PA. Current and Future Trends in Liver Transplantation in Europe. Gastroenterology. 2010;138(3):802-809.e4. doi:10.1053/j.gastro.2010.01.030
8. Cambridge Dictionary. https://dictionary.cambridge.org/dictionary/english/
9. Freeman RB, Edwards EB. Liver transplant waiting time does not correlate with waiting list mortality: Implications for liver allocation policy. Liver Transplant. 2000;6(5):543-552. doi:10.1053/jlts.2000.9744
10.	Organ Procurement and Transplantation Network--HRSA. Final Rule with Comment Period.; 1998.
11.	Steyerberg EW, Vickers AJ, Cook NR, et al. Assessing the performance of prediction models: A framework for traditional and novel measures. Epidemiology. 2010;21(1):128-138. doi:10.1097/EDE.0b013e3181c30fb2
12.	Clark TG, Bradburn MJ, Love SB, Altman DG. Survival Analysis Part I: Basic concepts and first analyses. Br J Cancer. 2003;89(2):232-238. doi:10.1038/sj.bjc.6601118
13.	Cox DR. Regression Models and Life-Tables. J ofthe R Stat Soc. 1972;34(2):187-220. doi:10.1016/0006-8993(85)91540-9
14.	Van Calster B, Nieboer D, Vergouwe Y, De Cock B, Pencina MJ, Steyerberg EW. A calibration hierarchy for risk models was defined: From utopia to empirical data. J Clin Epidemiol. 2016;74:167-176. doi:10.1016/j.jclinepi.2015.12.005
15.	Van Calster B, McLernon DJ, Van Smeden M, et al. Calibration: The Achilles heel of predictive analytics. BMC Med. 2019;17(1):1-7. doi:10.1186/s12916-019-1466-7
16.	Pugh R, Murray-Lyon I, Dawson JL, Pietroni MC, Williams R. Transection of the oesophagus for bleeding oesophageal varices. Br J Surg. 1973;60(8):646-649.
17.	Durand F, Valla D. Assessment of the prognosis of cirrhosis: Child-Pugh versus MELD. J Hepatol. 2005;42(SUPPL. 1):100-107. doi:10.1016/j.jhep.2004.11.015
18.	Malinchoc M, Kamath PS, Gordon FD, Peine CJ, Rank J, Ter Borg PCJ. A model to predict poor survival in patients undergoing transjugular intrahepatic portosystemic shunts. Hepatology. 2000;31(4):864-871. doi:10.1053/he.2000.5852
19.	Kamath PS, Wiesner RH, Malinchoc M, et al. A model to predict survival in patients with end-stage liver disease. Hepatology. 2001;33(2):464-470. doi:10.1053/jhep.2001.22172
20.	Wiesner R, Edwards E, Freeman R, et al. Model for end-stage liver disease (MELD) and allocation of donor livers. Gastroenterology. 2003;124(1):91-96. doi:10.1053/gast.2003.50016
21.	Kim WR, Biggins SW, Kremers WK, et al. Hyponatremia and Mortality among Patients on the Liver-Transplant Waiting List. N Engl J Med. 2008;359(10):1018-1026. doi:10.1007/s11250-017-1262-3
22.	Ginés P, Berl T, Bernardi M, et al. Hyponatremia in cirrhosis: From pathogenesis to treatment. Hepatology. 1998;28(3):851-864. doi:10.1002/hep.510280337
23.	Angeli P, Wong F, Watson H, et al. Hyponatremia in cirrhosis: Results of a patient population survey. Hepatology. 2006;44(6):1535-1542. doi:10.1002/hep.21412
24.	Biggins SW, Rodriguez HJ, Bacchetti P, Bass NM, Roberts JP, Terrault NA. Serum sodium predicts mortality in patients listed for liver transplantation. Hepatology. 2005;41(1):32-39. doi:10.1002/hep.20517
25.	Biggins SW, Kim WR, Terrault NA, et al. Evidence-Based Incorporation of Serum Sodium Concentration Into MELD. Gastroenterology. 2006;130(6):1652-1660. doi:10.1053/j.gastro.2006.02.010
26.	Ruf AE, Kremers WK, Chavez LL, Descalzi VI, Podesta LG, Villamil FG. Addition of serum sodium into the MELD score predicts waiting list mortality better than MELD alone. Liver Transplant. 2005;11(3):336-343. doi:10.1002/lt.20329
27.	Nagai S, Chau LC, Schilke RE, et al. Effects of Allocating Livers for Transplantation Based on Model for End-Stage Liver Disease-Sodium Scores on Patient Outcomes. Gastroenterology. 2018;155(October):1451-1482. doi:10.1053/j.gastro.2018.07.025
28.	Godfrey EL, Malik TH, Lai JC, et al. The decreasing predictive power of MELD in an era of changing etiology of liver disease. Am J Transplant. 2019;19(12):3299-3307. doi:10.1111/ajt.15559
29.	Leise MD, Kim WR, Kremers WK, Larson JJ, Benson JT, Therneau TM. A revised model for end-stage liver disease optimizes prediction of mortality among patients awaiting liver transplantation. Gastroenterology. 2011;140(7):1952-1960. doi:10.1053/j.gastro.2011.02.017
30.	Sharma P, Schaubel DE, Sima CS, Merion RM, Lok ASF. Re-weighting the Model for End-Stage Liver Disease Score Components. Gastroenterology. 2008;135(5):1575-1581. doi:10.1053/j.gastro.2008.08.004
31.	Rizopoulos R. Joint Models for Longitudinal and Time-to-Event Data: With Applications in R. 1st ed. Chapman and Hall/CRC; 2012.
32.	Arroyo V, Moreau R, Jalan R. Acute-on-Chronic Liver Failure. N Engl J Med. 2020;(382):2137-2145. doi:10.1056/NEJMra1914900
33.	Hernaez R, Liu Y, Kramer JR, Rana A, El-Serag HB, Kanwal F. Model for end-stage liver disease-sodium underestimates 90-day mortality risk in patients with acute-on-chronic liver failure. J Hepatol. Published online 2020:1-9. doi:10.1016/j.jhep.2020.06.005
34.	Goudsmit BFJ, Tushuizen ME, Putter H, Braat AE, van Hoek B. The role of the model for end-stage liver disease-sodium score and joint models for 90-day mortality prediction in patients with acute-on-chronic liver failure. J Hepatol. 2021;74(2):475-476. doi:10.1016/j.jhep.2020.08.032
35.	Cillo U, Vitale A, Polacco M, Fasolo E. Liver transplantation for hepatocellular carcinoma through the lens of transplant benefit. Hepatology. 2017;65(5):1741-1748. doi:10.1002/hep.28998
36.	Merion RM, Schaubel DE, Dykstra DM, Freeman RB, Port FK, Wolfe RA. The survival benefit of liver transplantation. Am J Transplant. 2005;5(2):307-313. doi:10.1111/j.1600-6143.2004.00703.x
37.	Martin P, Dimartini A, Feng S, Brown R, Fallon M. Evaluation for liver transplantation in adults: 2013 practice guideline by the American Association for the Study of Liver Diseases and the American Society of Transplantation. Hepatology. 2014;59(3):1144-1165. doi:10.1002/hep.26972
38.	Petrowsky H, Rana A, Kaldas FM, et al. Liver transplantation in highest acuity recipients: Identifying factors to avoid futility. Ann Surg. 2014;259(6):1186-1194. doi:10.1097/SLA.0000000000000265
39.	Linecker M, Krones T, Berg T, et al. Potentially inappropriate liver transplantation in the era of the “sickest first” policy – A search for the upper limits. J Hepatol. 2018;68(4):798-813. doi:10.1016/j.jhep.2017.11.008
40.	Vitale A, Volk ML, De Feo TM, et al. A method for establishing allocation equity among patients with and without hepatocellular carcinoma on a common liver transplant waiting list. J Hepatol. 2014;60(2):290-297. doi:10.1016/j.jhep.2013.10.010
41.	Berry K, Ioannou GN. Comparison of Liver Transplant-Related Survival Benefit in Patients with Versus Without Hepatocellular Carcinoma in the United States. Gastroenterology. 2015;149(3):669-680. doi:10.1053/j.gastro.2015.05.025
42.	Freeman RB, Gish RG, Harper A, et al. Model for End-Stage Liver Disease (MELD) Exception Guidelines: Results and Recommendations From the MELD Exception Study Group and Conference (MESSAGE) for the Approval of Patients Who Need Liver Transplantation With Diseases Not Considered by the Standar. Liver Transplant. 2007;13(5):767-768. doi:10.1002/lt
43.	Massie AB, Caffo B, Gentry SE, et al. MELD exceptions and rates of waiting list outcomes. Am J Transplant. 2011;11(11):2362-2371. doi:10.1111/j.1600-6143.2011.03735.x
44.	Washburn K, Edwards E, Harper A, Freeman RB. Hepatocellular Carcinoma Patients Are Advantaged in the Current Liver Transplant Allocation System. Am J Transplant. 2010;10(7):1652-1657. doi:10.1111/j.1600-6143.2010.03127.x
45.	Northup PG, Intagliata NM, Shah NL, Pelletier SJ, Berg CL, Argo CK. Excess mortality on the liver transplant waiting list: Unintended policy consequences and model for End-Stage Liver Disease (MELD) inflation. Hepatology. 2015;61(1):285-291. doi:10.1002/hep.27283

\newpage
\linespread{1.213}
\normalsize
\thispagestyle{plain}
\mbox{}
