<!-- tinytex::tlmgr_install("hyphen-dutch") -->
\backmatter
\selectlanguage{dutch}
\pagecolor{black}
\color{white}

# Nederlandse samenvatting (Summary in Dutch) {#chap-nlsum}
\chaptermark{Summary in Dutch}

\newpage
\nopagecolor
\color{black}

## Verbetering van voorspellingsmodellen voor levertransplantatiekandidaten {-}

\bigskip
<br>

Een levertransplantatie is levensreddend voor patiënten met een leverziekte. Omdat niet iedere patiënt (direct) kan worden geholpen, worden patiënten op een wachtlijst geplaatst. Op deze wachtlijst wordt de volgorde bepaald door de ernst van de ziekte: de ziekste patiënten gaan eerst. De ziekte-ernst wordt ingeschat door de toekomstige wachtlijstoverleving te berekenen. Hoe lager de toekomstige wachtlijstoverleving, hoe hoger de prioriteit. De methode van het inschatten van overleving is dus van levensbelang voor deze patiënten. Dit proefschrift onderzoekt nieuwe modellen voor het voorspellen van de overleving rond levertransplantatie.

### Deel I {-}
In **Hoofdstuk \@ref(chap-meldna)** werd een verbetering onderzocht van het huidige model dat de wachtlijstvolgorde bepaalt: de 'Model for End-stage Liver Disease' (MELD) score. Specifiek werd onderzocht of het uitbreiden van de MELD score met natrium (MELD-Na) een verbetering zou geven van de sterftevoorspelling op de wachtlijst. We vonden dat een laag natrium (hyponatriëmie) de kans op wachtlijststerfte verhoogt. Patiënten met een natrium van 125 mmol/L hebben een 2.9 (95%CI 2.30-3.53; p<0.001) keer grotere kans op sterfte binnen 90 dagen dan patiënten met een normaal (140 mmol/L) natrium. Vergeleken met de MELD score was de MELD-Na score  een significant betere voorspeller van overleving, met een een c-index van respectievelijk 0.832 en 0.847. Een c-index waarde dichter bij de 1.0 is beter en betekent dat een model beter patiënten kan rangschikken op de wachtlijst van meest naar minst ziek. Waarschijnlijk zal het gebruik van de MELD-Na score voor leverallocatie de wachtlijststerfte verlagen omdat de mate van hyponatriëmie wordt meegenomen en dus wachtlijststerfte preciezer wordt ingeschat. 

Aangezien de huidige vorm van de MELD score 20 jaar geleden werd ontworpen in de Verenigde Staten, werd in **Hoofdstuk \@ref(chap-refit)** onderzocht of het herwegen van de MELD score in de Eurotransplant regio een betere overlevingsvoorspelling zou geven. Het lijkt gek om een Amerikaans model te gebruiken om Europese patiënten te prioriteren. We onderzochten de relatie van de MELD parameters (serum kreatinine, bilirubine en de INR) en het natrium met de 90-daagse overlijdingskans op de wachtlijst. We vonden dat nieuwe afkapwaardes voor de MELD parameters en het natrium resulteerden in significant betere modellen: de refit MELD en refit MELD-Na. De nieuwe modellen waren preciezer in het rangschikken van patiënten op de wachtlijst. Vergeleken met de MELD, prioriteerde de refit MELD-Na score patiënten met een 1.6 keer hogere 90-daagse wachtlijststerfte. Op basis van de refit modellen zouden donorlevers dus beter verdeeld kunnen worden omdat de ziekste patiënten beter geïdentificeerd kunnen worden. Hierdoor zou sterfte op de wachtlijst kunnen worden voorkomen.

### Deel II {-}
In het tweede deel van dit proefschrift werden metingen over de tijd gebruikt om tegelijkertijd ziekte en overleving te modelleren. Het idee was om een betere benadering te geven van de manier waarop een arts de prognose van een patiënt inschat. Een arts zal altijd het ziekteverloop uit het verleden meenemen om de prognose in te schatten. Het is daarom onlogisch dat de huidige modellen die wachtlijstvolgorde bepalen alle voorgaande beschikbare metingen negeren, net als een arts die niet meer weet wat er gisteren is gebeurd. Met de techniek van joint models (JMs) namen we alle beschikbare data over de tijd mee in voorspellingen van overleving. Hierbij werd gekeken naar zowel de gemeten ziekte-ernst als de mate van verandering. Een analogie voor ziekte-ernst en verandering is hardlopen. Je kunt met een bepaalde snelheid rennen (bijvoorbeeld 3 m/s) en daarbij versnellen (bijvoorbeeld met 1 m/s^2^) of vertragen. De verandering geeft dus mogelijk belangrijke informatie over ziekte.

**Hoofdstuk \@ref(chap-jm)** toont de eerste toepassing van JMs in levertransplantatiekandidaten. De analyse van MELD(-Na) metingen over de tijd werd gecombineerd met overlevingsanalyse. Hierdoor kon het effect van ziekteverandering over de tijd op overleving worden bestudeerd. We vonden dat zowel de gemeten MELD(-Na) score als de mate van verandering over de tijd een belangrijke invloed hadden op wachtlijstoverleving. De JMs waren significant beter in het voorspellen van wachtlijststerfte dan de huidige modellen die wachtlijstvolgorde bepalen. De JMs zijn een belangrijke verbetering omdat alle beschikbare metingen over de tijd werden gebruikt, waarbij zowel de ziekte-ernst als de mate van verandering werden meegenomen, zodat persoonlijke voorspellingen konden worden gedaan. Ook werden de voorspellingsmodellen in een online applicatie geplaatst, waarmee gebruikers data van individuele patiënten kunnen uploaden om JM voorspellingen te krijgen voor wachtlijstoverleving.

In **Hoofdstuk \@ref(chap-aclfjm)** onderzochten we hoe de JMs, die nieuwe voorspellingen maken voor elke nieuwe meting over de tijd, overleving voorspelden in patiënten met Acute-on-Chronic Liver Failure (ACLF). ACLF is een dodelijke ziekte die snel verandert over de tijd. Daarom is het belangrijk dat een voorspellingsmodel meeverandert, hetgeen een JM kan. We vonden dat een aanzienlijk deel van de patiënten op de leverwachtlijst een vorm van ACLF had. Het huidige model dat overleving voorspelt (MELD-Na score) had een slechte c-index (capaciteit tot rangschikken op de wachtlijst) met oplopende ziekte-ernst. Hierdoor wordt de huidige wachtlijstprioriteit minder nauwkeurig in ziekere patiënten. Dit is ongewenst. De JMs waren nauwkeuriger en bleven dat ook in de ziekste patiënten. Met de JMs konden nauwkeurigere voorspellingen worden gegeven, voor zowel de populatie als het individu.

### Deel III {-}
In het laatste deel en **Hoofdstuk \@ref(chap-benefit)** onderzochten we hoeveel levenswinst patiënten kregen door levertransplantatie. Het verschil in overleving met en zonder levertransplantatie werd berekend en vergeleken tussen patiënten met en zonder hepatocellulair carcinoom (HCC). We vonden dat patiënten met HCC een hogere wachtlijststerfte hadden en meestal bij lagere MELD(-Na) scores werden getransplanteerd dan niet-HCC patiënten. Doordat HCC patiënten bij lagere MELD(-Na) werden getransplanteerd, haalden ze minder levenswinst uit levertransplantatie dan niet-HCC patiënten, die vooral bij hogere MELD(-Na) scores werden getransplanteerd. Leverfunctie was de belangrijkste voorspeller van overlevingswinst en daarom kregen patiënten zonder HCC gemiddeld meer levensjaren van transplantatie. Gezien de schaarste van donor levers zou men dus kunnen overwegen om HCC patiënten zoveel als mogelijk zonder levertransplantatie te behandelen.

Concluderend werden er in dit proefschrift modellen onderzocht die overleving voorspellen in levertransplantatie. De statistisch significante en klinisch relevante verbeteringen kunnen worden gebruikt om de huidige leverallocatie te verbeteren.

\newpage
\thispagestyle{plain}
\mbox{}