# Dankwoord {-}
\chaptermark{Dankwoord}

Tot slot een woord van dank. De afgelopen jaren heb ik me mogen verdiepen in het onderzoek naar voorspellingsmodellen in levertransplantatie. Dit is mogelijk geweest door een groot aantal mensen, maar ik wil met name de volgende personen bedanken:

Beste dr. Braat, beste Dries, door jou is dit alles begonnen. Je hebt me enthousiast gemaakt voor de complexe wereld van het transplantatie-onderzoek en je hebt me geholpen aan mijn eerste baan. Je geduldige begeleiding, visie, koppigheid en humor zijn onmisbaar geweest voor de totstandkoming van dit proefschrift.

Beste prof. Van Hoek, beste Bart, vanaf het begin was het voor mij duidelijk dat je een betrokken arts en begeleider bent. Je oprechte interesse en enthousiasme voor mijn onderzoek zijn een grote steun geweest. 

Beste prof. Putter, beste Hein, je bent een tovenaar. Ik ben begonnen met R doordat ik de magie wilde leren die ik je wekelijks zag programmeren. Dit heeft mijn onderzoek ongetwijfeld verrijkt en verdiept. Door jouw wekelijkse sturing is dit alles mogelijk geworden.

Beste dr. Tushuizen, beste Maarten, je geloofde in de potentie van mijn ideeën en was altijd bereid om snel en nauwkeurig mee te denken en mijn manuscripten te lezen. Alleen PhD'ers kunnen volledig waarderen hoe waardevol dat is.

Geachte leden van de leescommissie en de oppositie. Dank voor jullie instemmen met en het verdiepen in mijn proefschrift. Het is een eer de gelijktijdige aandacht te krijgen van zo veel scherpe geesten.

Beste collega PhD'ers, dank voor de (on)zinnige praat, de mooie reizen en avonden die we samen hebben gehad. Met name dank aan Jaap en Fenna voor alle extra begeleiding.

The author thanks the Eurotransplant Liver and Intestine Advisory Committee (ELIAC) members for their critical appraisal and approval of several study protocols.

De medische staf van Eurotransplant, dank voor alle lessen die jullie me geleerd hebben. 

De allocatiemedewerkers, Olga, en alle anderen bij Eurotransplant, dank voor alle mooie gesprekken en goede sfeer.

Mijn vrienden van de trip, vanaf het begin zat het goed, het is mooi zo'n breed palet aan mensen te kennen binnen ons vakgebied.

Hamëz, je werklust, talent en humor zijn onmisbare motivatoren geweest.

Mijn goede vrienden van Nexus, jullie karakters zijn goud waard, dank voor alle mooie tijden die waren en die nog komen.

Daan, vriend van het eerste uur, dank voor al je steun tijdens deze PhD. Samen hetzelfde pad doorlopen doet me nog steeds iedere dag deugd.

Mijn huisgenoten de laatste jaren, Sjors en Leon, dank voor de afleiding en verdieping die jullie me gaven.

Mijn ouders. Jullie trots en geloof in mij vormen een ononderbroken steun.

Mijn zussen, we zijn allemaal andere paden ingeslagen en daardoor is mijn leven zoveel rijker geworden, dank voor jullie geduld en warmte.

Fleur, licht van mijn leven. Je viert elke dag en leert me te genieten. Samen met jou kijk ik uit naar alles wat nog komt.
